"""Domain models for ISR Platform."""

from dataclasses import dataclass, field
from datetime import datetime
from typing import Any
from uuid import UUID, uuid4

from .enums import (
    AlertCategory,
    AlertStatus,
    AnomalyDomain,
    EntityStatus,
    EntityType,
    EventType,
    Severity,
    SourceType,
    ThreatCategory,
)


@dataclass
class GeoPoint:
    """Geographic point with coordinates."""

    latitude: float
    longitude: float
    altitude: float | None = None
    accuracy: float | None = None


@dataclass
class DataSource:
    """Attribution to a data source."""

    source_type: SourceType
    source_id: str
    weight: float = 1.0
    confidence: float = 0.5
    timestamp: datetime | None = None


@dataclass
class Entity:
    """A tracked entity (vehicle, personnel, facility, etc.)."""

    entity_id: UUID = field(default_factory=uuid4)
    entity_type: EntityType = EntityType.UNKNOWN
    entity_subtype: str | None = None
    display_name: str | None = None
    status: EntityStatus = EntityStatus.ACTIVE
    confidence_score: float = 0.5
    first_observed: datetime = field(default_factory=datetime.utcnow)
    last_observed: datetime = field(default_factory=datetime.utcnow)
    current_position: GeoPoint | None = None
    attributes: dict[str, Any] = field(default_factory=dict)
    created_at: datetime = field(default_factory=datetime.utcnow)
    updated_at: datetime = field(default_factory=datetime.utcnow)


@dataclass
class Event:
    """A security or humanitarian event."""

    event_id: UUID = field(default_factory=uuid4)
    event_type: EventType = EventType.OTHER
    event_subtype: str | None = None
    severity: Severity = Severity.MEDIUM
    occurred_at: datetime | None = None
    reported_at: datetime = field(default_factory=datetime.utcnow)
    location: GeoPoint | None = None
    location_description: str | None = None
    region: str | None = None
    province: str | None = None
    district: str | None = None
    title: str = ""
    summary: str | None = None
    details: dict[str, Any] = field(default_factory=dict)
    casualties_killed: int | None = None
    casualties_wounded: int | None = None
    population_affected: int | None = None
    verification_status: str = "UNVERIFIED"
    sources: list[DataSource] = field(default_factory=list)


@dataclass
class Alert:
    """An alert generated by the platform."""

    alert_id: UUID = field(default_factory=uuid4)
    category: AlertCategory = AlertCategory.SECURITY
    subcategory: str | None = None
    severity: Severity = Severity.MEDIUM
    title: str = ""
    summary: str = ""
    details: dict[str, Any] = field(default_factory=dict)
    location: GeoPoint | None = None
    region: str | None = None
    threat_score: int | None = None
    confidence: float = 0.5
    trigger_type: str = ""
    trigger_id: str | None = None
    sources: list[DataSource] = field(default_factory=list)
    status: AlertStatus = AlertStatus.OPEN
    assigned_to_user: str | None = None
    assigned_to_team: str | None = None
    response_deadline: datetime | None = None
    resolution_deadline: datetime | None = None
    related_entities: list[UUID] = field(default_factory=list)
    related_events: list[UUID] = field(default_factory=list)
    created_at: datetime = field(default_factory=datetime.utcnow)
    updated_at: datetime = field(default_factory=datetime.utcnow)
    acknowledged_at: datetime | None = None
    resolved_at: datetime | None = None
    resolved_by: str | None = None
    resolution_notes: str | None = None


@dataclass
class ThreatScore:
    """Calculated threat score for an entity."""

    entity_id: UUID
    overall_score: int
    category: ThreatCategory
    factor_scores: dict[str, dict[str, Any]]
    explanation_summary: str | None = None
    key_indicators: list[str] = field(default_factory=list)
    recommendations: list[str] = field(default_factory=list)
    model_id: str | None = None
    model_version: str | None = None
    context_window_start: datetime | None = None
    context_window_end: datetime | None = None
    trend_direction: str | None = None
    calculated_at: datetime = field(default_factory=datetime.utcnow)


@dataclass
class Anomaly:
    """A detected anomaly."""

    anomaly_id: UUID = field(default_factory=uuid4)
    domain: str = ""
    anomaly_subtype: str | None = None
    severity: Severity = Severity.MEDIUM
    severity_score: int = 50
    detected_at: datetime = field(default_factory=datetime.utcnow)
    location: GeoPoint | None = None
    region: str | None = None
    description: str = ""
    baseline_stats: dict[str, Any] = field(default_factory=dict)
    model_id: str | None = None
    model_version: str | None = None
    anomaly_score: float = 0.0
    related_entities: list[UUID] = field(default_factory=list)
    related_events: list[UUID] = field(default_factory=list)
    status: str = "OPEN"


@dataclass
class User:
    """A platform user."""

    user_id: UUID = field(default_factory=uuid4)
    username: str = ""
    email: str | None = None
    display_name: str | None = None
    password_hash: str = ""
    organization: str | None = None
    roles: list[str] = field(default_factory=list)
    status: str = "ACTIVE"
    created_at: datetime = field(default_factory=datetime.utcnow)
    last_login: datetime | None = None
